version: '3.8'

services:
  database:
    build:
      context: .
      dockerfile: docker/postgres/Dockerfile
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
    networks:
      web-app:

  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      target: http-server
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "8118:80"
    volumes:
      - ./resources:/app/resources
      - ./src:/app/src
      - ./tests:/app/tests
    environment:
      - PROFILES=default,dev,docker
    networks:
      web-app:

  toolbox:
    deploy:
      replicas: 0
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      target: php-toolbox
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ./resources:/app/resources
      - ./src:/app/src
      - ./tests:/app/tests
    environment:
      - PROFILES=default,dev,docker
    networks:
      web-app:

volumes:
  pgdata:

networks:
  web-app:
