services:
  database:
    ports:
      - "5432:5432"

  app:
    ports:
      - "8118:80"
      - "9118:443"
    volumes:
      - ./app.php:/app/app.php
      - ./resources:/app/resources
      - ./src:/app/src
      - ./tests:/app/tests

  toolbox:
    volumes:
      - .:/app
