name: 'Unit Tests & Static Analysis'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit-testing:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: xdebug
          tools: composer:2
          ini-file: development
      - name: Setup problem matchers for PHP
        run: echo "::add-matcher::${{ runner.tool_cache }}/php.json"
      - name: Setup problem matchers for PHPUnit
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"
      - name: Composer
        run: composer install
      - name: Composer (Testing Tools)
        run: cd tools/phpunit && composer install
      - name: Unit Testing
        env:
          XDEBUG_MODE: coverage
        run: ./tools/phpunit/vendor/bin/phpunit

  static-analysis:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: composer:2
      - name: Setup problem matchers for PHP
        run: echo "::add-matcher::${{ runner.tool_cache }}/php.json"
      - name: Composer
        run: composer install
      - name: Composer (Static Analysis Tools)
        run: cd tools/psalm && composer install
      - name: Static Analysis
        run: ./tools/psalm/vendor/bin/psalm --output-format=github
